# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Host-neutral runtime projections consumed by interactive frontends."""

from __future__ import annotations

import asyncio
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any, Protocol

from nooa_cli.interactive.state import InteractiveAgent


@dataclass(frozen=True, slots=True)
class JobSnapshot:
    """Immutable background-job projection safe for frontend consumption."""

    name: str
    label: str
    state: str
    queued: int
    values: tuple[Any, ...]


class AgentRuntime(InteractiveAgent, Protocol):
    """Narrow lifecycle/runtime service used by a local interactive host.

    This intentionally describes host operations rather than exposing concrete
    queues, event loops, or agents. The inherited ``InteractiveAgent`` surface is portable; the additional
    methods are local composition-root lifecycle services.
    """

    @property
    def is_thinking(self) -> bool: ...

    @property
    def cancel_requested(self) -> bool: ...

    @property
    def task(self) -> asyncio.Future[Any] | None: ...

    def set_dispatch_hooks(
        self,
        *,
        on_state_change: Callable[[], None] | None = None,
        on_before_handle: Callable[[Any], Awaitable[None] | None] | None = None,
        on_after_handle: Callable[[Any, Any], Awaitable[None] | None] | None = None,
        on_notification: Callable[[dict[str, list[Any]]], None] | None = None,
        dispatcher_exit: type[BaseException] | None = None,
        on_cancelled: Callable[[], None] | None = None,
    ) -> None: ...
    def bind(self) -> None: ...
    def set_user_message_accepted_callback(
        self, callback: Callable[[str], None] | None
    ) -> None: ...
    def activate(self, ui_loop: asyncio.AbstractEventLoop) -> None: ...
    def submit(self, text: str) -> bool: ...
    def request_cancel(self, *, force: bool = False, notify: bool = True) -> bool: ...
    async def cancel_turn(self, *, force: bool = False, notify: bool = True) -> bool: ...
    async def cancel_for_transition(self) -> bool: ...
    async def swap_agent(self, agent: Any) -> None: ...
    def seed_and_swap(self, agent: Any, prompt: str) -> Awaitable[None]: ...
    def submit_slash_result(self, result: Any) -> bool: ...
    def pending_user_messages(self) -> tuple[str, ...]: ...
    def queue_continuation(self, text: str) -> str | None: ...
    def cancel_tasks(self, tasks: list[asyncio.Task[Any]]) -> None: ...
    def job_snapshots(self) -> tuple[JobSnapshot, ...]: ...
    def run(self, fn: Callable[[], Any]) -> Any: ...
    async def run_async(self, fn: Callable[[], Any]) -> Any: ...
    async def shutdown_queue_manager(self, *, flush: bool = False) -> None: ...
    async def shutdown(self) -> None: ...
